# Generated by Skyramp v1.3.27 on 2026-06-15 10:55:25.860048754 +0000 UTC m=+262.523772500
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output app_messages_delete_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb/gotify-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb/gotify-testb/tests/skyramp/scenario_app-messages-delete-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8090")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    application = "1"

    # Request Body
    application_POST_request_body = r'''{
        "description": "Test application for delete",
        "name": "DeleteTestApp-1234567890"
    }'''
    
    # Execute Request
    application_POST_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )
    # Generated Assertions
    assert application_POST_response.status_code == 201
    assert skyramp.get_response_value(application_POST_response, "name") == "DeleteTestApp-1234567890"
    assert skyramp.get_response_value(application_POST_response, "description") == "Test application for delete"
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None
    application = skyramp.get_response_value(application_POST_response, "id")

    # Execute Request
    message_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/application/{application}/message",
        method="DELETE",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        path_params={"application": application}
    )
    # Generated Assertions
    assert message_DELETE_response.status_code == 200


if __name__ == "__main__":
    test_integration()
