# Generated by Skyramp v1.3.27 on 2026-06-15 10:59:12.257053581 +0000 UTC m=+486.539667005
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output application_update_verify_token_prefix_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb/gotify-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb/gotify-testb/tests/skyramp/scenario_application-update-verify-token-prefix.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8090")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    application = "1"

    # Request Body
    application_POST_request_body = r'''{
        "description": "Token prefix update test",
        "name": "updatetest-1718000000"
    }'''
    
    # Execute Request
    application_POST_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )
    # Generated Assertions
    assert application_POST_response.status_code == 200
    assert skyramp.get_response_value(application_POST_response, "name") == "updatetest-1718000000"
    assert skyramp.get_response_value(application_POST_response, "description") == "Token prefix update test"
    assert skyramp.get_response_value(application_POST_response, "internal") == False
    assert skyramp.get_response_value(application_POST_response, "defaultPriority") == 0
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None
    assert skyramp.get_response_value(application_POST_response, "tokenPrefix") is not None
    assert skyramp.get_response_value(application_POST_response, "tokenPrefix") == skyramp.get_response_value(application_POST_response, "token")[:4]
    assert re.match(r'^\d{4}-\d{2}-\d{2}T', skyramp.get_response_value(application_POST_response, "createdAt"))

    # Request Body
    application_application_PUT_request_body = r'''{
        "name": "updated-updatetest-1718000000"
    }'''
    
    # Execute Request
    application_application_PUT_response = client.send_request(
        url=URL_localhost,
        path="/application/{application}",
        method="PUT",
        body=application_application_PUT_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        path_params={"application": application}
    )
    # Generated Assertions
    assert application_application_PUT_response.status_code == 200
    assert skyramp.get_response_value(application_application_PUT_response, "name") == "updated-updatetest-1718000000"
    assert skyramp.get_response_value(application_application_PUT_response, "id") == skyramp.get_response_value(application_POST_response, "id")
    assert skyramp.get_response_value(application_application_PUT_response, "token") == skyramp.get_response_value(application_POST_response, "token")
    assert skyramp.get_response_value(application_application_PUT_response, "tokenPrefix") == skyramp.get_response_value(application_POST_response, "tokenPrefix")
    assert skyramp.get_response_value(application_application_PUT_response, "tokenPrefix") == skyramp.get_response_value(application_application_PUT_response, "token")[:4]

    # Execute Request
    application_GET_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="GET",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )
    # Generated Assertions
    assert application_GET_response.status_code == 200
    assert skyramp.get_response_value(application_GET_response, "0.id") == skyramp.get_response_value(application_POST_response, "id")
    assert skyramp.get_response_value(application_GET_response, "0.name") == "updated-updatetest-1718000000"
    assert skyramp.get_response_value(application_GET_response, "0.tokenPrefix") == skyramp.get_response_value(application_POST_response, "tokenPrefix")
    assert skyramp.get_response_value(application_GET_response, "0.token") == skyramp.get_response_value(application_POST_response, "token")


if __name__ == "__main__":
    test_integration()
