# Generated by Skyramp v1.3.27 on 2026-06-15 10:54:58.667865241 +0000 UTC m=+235.331588976
# Command: skyramp generate contract rest http://localhost:8090/application/{id}/message \
# 		--api-schema http://localhost:8090/swagger \
# 		--auth-header X-Gotify-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_application_message_get_404_test.py \
# 		--output-dir /home/runner/work/gotify-testb/gotify-testb/tests/skyramp \
# 		--overwrite \
# 		--path-params id=99999 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8090")

# contract test for /application/{id}/message GET
def test_message_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Gotify-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "99999"

    # Expected Response Body
    expected_message_GET_response_body = r'''{
        "error": "Not Found",
        "errorCode": 404,
        "errorDescription": "application does not exist"
    }'''

    # Execute Request
    message_GET_response = client.send_request(
        url=URL,
        path="/application/{id}/message",
        method="GET",
        headers=headers,
        path_params={"id": id},
        query_params={
            "limit": 100,
            "since": None
        }
    )

    # Generated Assertions
    assert message_GET_response.status_code == 404
    assert skyramp.check_schema(message_GET_response, expected_message_GET_response_body)
    assert skyramp.get_response_value(message_GET_response, "error") is not None
    assert skyramp.get_response_value(message_GET_response, "errorCode") is not None
    assert skyramp.get_response_value(message_GET_response, "errorDescription") is not None
    assert skyramp.get_response_value(message_GET_response, "error") == "Not Found"
    assert skyramp.get_response_value(message_GET_response, "errorCode") == 404
    assert skyramp.get_response_value(message_GET_response, "errorDescription") == "application does not exist"


if __name__ == "__main__":
    test_message_get()
