# Generated by Skyramp v1.3.27 on 2026-06-15 11:00:27.757775811 +0000 UTC m=+525.935363688
# Command: skyramp generate contract rest http://localhost:8090/message \
# 		--api-schema http://localhost:8090/swagger \
# 		--auth-header X-Gotify-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/gotify-testb/gotify-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--query-params priority=2 \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8090")

# contract test for /message GET
def test_message_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Gotify-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_message_GET_response_body = r'''{
        "messages": [
            {
                "appid": 5,
                "date": "2018-02-27T19:36:10.5045044+01:00",
                "id": 25,
                "message": "**Backup** was successfully finished."
            }
        ],
        "paging": {
            "limit": 123,
            "since": 5,
            "size": 5
        }
    }'''

    # Execute Request
    message_GET_response = client.send_request(
        url=URL,
        path="/message",
        method="GET",
        headers=headers,
        query_params={"priority": "2"}
    )

    # Generated Assertions
    assert message_GET_response.status_code == 200
    assert skyramp.check_schema(message_GET_response, expected_message_GET_response_body)
    assert skyramp.get_response_value(message_GET_response, "messages.0.appid") is not None
    assert skyramp.get_response_value(message_GET_response, "messages.0.date") is not None
    assert skyramp.get_response_value(message_GET_response, "messages.0.id") is not None
    assert skyramp.get_response_value(message_GET_response, "messages.0.id") > 0
    assert skyramp.get_response_value(message_GET_response, "paging.size") >= 0
    assert skyramp.get_response_value(message_GET_response, "paging.limit") >= 1
    assert skyramp.get_response_value(message_GET_response, "messages.0.priority") == 2
    assert "T" in skyramp.get_response_value(message_GET_response, "messages.0.date")


if __name__ == "__main__":
    test_message_get()
