# Generated by Skyramp v1.3.27 on 2026-06-15 10:58:55.01765658 +0000 UTC m=+455.237069360
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output message_count_after_app_create_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb/gotify-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb/gotify-testb/tests/skyramp/scenario_message_count_after_app_create.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8090")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    application_POST_request_body = r'''{
        "name": "TestApp-count-test"
    }'''
    
    # Execute Request
    application_POST_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )
    # Generated Assertions
    assert application_POST_response.status_code == 200
    assert skyramp.get_response_value(application_POST_response, "name") == "TestApp-count-test"
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None
    assert skyramp.get_response_value(application_POST_response, "description") == ""
    assert skyramp.get_response_value(application_POST_response, "internal") == False
    assert skyramp.get_response_value(application_POST_response, "defaultPriority") == 0

    # Execute Request
    count_GET_response = client.send_request(
        url=URL_localhost,
        path="/message/count",
        method="GET",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )
    # Generated Assertions
    assert count_GET_response.status_code == 200
    assert skyramp.get_response_value(count_GET_response, "count") >= 0


if __name__ == "__main__":
    test_integration()
