# Generated by Skyramp v1.3.27 on 2026-06-15 10:58:56.37933454 +0000 UTC m=+456.598747331
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output message_count_vs_list_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb/gotify-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb/gotify-testb/tests/skyramp/scenario_message_count_vs_list.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8090")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Execute Request
    message_GET_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="GET",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        query_params={"limit": ["100"]}
    )
    # Generated Assertions
    assert message_GET_response.status_code == 200
    assert skyramp.get_response_value(message_GET_response, "paging.limit") == 100
    assert skyramp.get_response_value(message_GET_response, "paging.size") >= 0

    # Execute Request
    count_GET_response = client.send_request(
        url=URL_localhost,
        path="/message/count",
        method="GET",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )
    # Generated Assertions
    assert count_GET_response.status_code == 200
    assert skyramp.get_response_value(count_GET_response, "count") >= 0
    assert skyramp.get_response_value(count_GET_response, "count") >= skyramp.get_response_value(message_GET_response, "paging.size")


if __name__ == "__main__":
    test_integration()
