# Generated by Skyramp v1.3.27 on 2026-06-15 10:58:45.05005695 +0000 UTC m=+445.269469740
# Command: skyramp generate contract rest http://localhost:8090/message/count \
# 		--auth-header X-Gotify-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output message_count_contract_test.py \
# 		--output-dir /home/runner/work/gotify-testb/gotify-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-data "{\"count\": 42}" \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8090")

# contract test for /message/count GET
def test_count_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Gotify-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_count_GET_response_body = r'''{"count": 42}'''

    # Execute Request
    count_GET_response = client.send_request(
        url=URL,
        path="/message/count",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert count_GET_response.status_code == 200
    assert skyramp.check_schema(count_GET_response, expected_count_GET_response_body)
    assert skyramp.get_response_value(count_GET_response, "count") >= 0


if __name__ == "__main__":
    test_count_get()
