# Generated by Skyramp v1.3.27 on 2026-06-15 11:02:22.889097357 +0000 UTC m=+641.066685234
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output message_priority_filter_happy_path_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb/gotify-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb/gotify-testb/tests/skyramp/scenario_message-priority-filter-happy-path.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8090")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    _token = os.getenv("SKYRAMP_TEST_TOKEN", "SKYRAMP_PLACEHOLDER_TOKEN")
    _auth_headers = {"X-Gotify-Key": _token}
    # Request Body
    application_POST_request_body = r'''{
        "name": "TestApp-PriorityFilter"
    }'''
    
    # Execute Request
    application_POST_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers=_auth_headers
    )
    # Generated Assertions
    assert application_POST_response.status_code == 201
    assert skyramp.get_response_value(application_POST_response, "name") == "TestApp-PriorityFilter"
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None

    # Request Body
    message_POST_request_body = r'''{
        "appid": 1,
        "message": "Test message with priority 2",
        "priority": 2,
        "title": "Priority 2 Message"
    }'''
    
    # Execute Request
    message_POST_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="POST",
        body=message_POST_request_body,
        headers=_auth_headers
    )
    # Generated Assertions
    assert message_POST_response.status_code == 200
    assert skyramp.get_response_value(message_POST_response, "priority") == 2
    assert skyramp.get_response_value(message_POST_response, "message") == "Test message with priority 2"
    assert skyramp.get_response_value(message_POST_response, "title") == "Priority 2 Message"
    assert skyramp.get_response_value(message_POST_response, "id") > 0

    # Request Body
    message_POST_1_request_body = r'''{
        "appid": 1,
        "message": "Test message with priority 5",
        "priority": 5,
        "title": "Priority 5 Message"
    }'''
    
    # Execute Request
    message_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="POST",
        body=message_POST_1_request_body,
        headers=_auth_headers
    )
    # Generated Assertions
    assert message_POST_1_response.status_code == 200
    assert skyramp.get_response_value(message_POST_1_response, "priority") == 5
    assert skyramp.get_response_value(message_POST_1_response, "message") == "Test message with priority 5"
    assert skyramp.get_response_value(message_POST_1_response, "title") == "Priority 5 Message"
    assert skyramp.get_response_value(message_POST_1_response, "id") > 0

    # Execute Request
    message_GET_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="GET",
        headers=_auth_headers,
        query_params={"priority": ["2"]}
    )
    # Generated Assertions
    assert message_GET_response.status_code == 200
    assert skyramp.get_response_value(message_GET_response, "paging.size") == 1
    assert skyramp.get_response_value(message_GET_response, "paging.limit") == 100
    assert skyramp.get_response_value(message_GET_response, "paging.next") == ""
    assert skyramp.get_response_value(message_GET_response, "messages.0.priority") == 2
    assert skyramp.get_response_value(message_GET_response, "messages.0.id") == skyramp.get_response_value(message_POST_response, "id")
    assert skyramp.get_response_value(message_GET_response, "messages.0.message") == "Test message with priority 2"
    assert skyramp.get_response_value(message_GET_response, "messages.1") is None


if __name__ == "__main__":
    test_integration()
